name: jakone_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  get: 4.6.6
  get_storage: ^2.1.1
  gradient_borders: ^1.0.0
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        # - asset: assets/fonts/nunito/Nunito-Thin.ttf
        #   weight: 100
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        # - asset: assets/fonts/nunito/Nunito-Italic.ttf
        #   style: italic
        #   weight: 700
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/icons/
    - assets/images/menus/
